### ISSUE TITLE
Lightning talks

### ISSUE THREAD

**Issue by pinage404** [lelionvert/ledessert#2]
démo à l'arrache de [`git bisect`](https://git-scm.com/docs/git-bisect)

**Comment by pinage404** [comment]
on a évoqué des crypto-monnaie

Duniter / Ğ1 la crypo-monnaie qui intègre un dividende universel
http://www.duniter.fr/presentation/
https://duniter.org/fr/comprendre/

@tbenett tu peux ajouter les liens vers celle dont tu as parlé stp ?

@udebella tu peux mettre le lien qui dit que Qwant c'est pas si top stp ?

**Comment by udebella** [comment]
L'article officiel est sur [médiapart](https://www.mediapart.fr/journal/economie/270819/qwant-les-parts-d-ombre-d-un-moteur-de-recherche-strategique?onglet=full), du coup c'est payant.
Par contre, y a eu des copié-collé sur [reddit](https://www.reddit.com/r/france/comments/cw1nrb/mediapart_qwant_la_part_dombre_dun_moteur_de/)

En le relisant, c'est pas si horrible que ça, mais ça a pas l'air ouf quand même.

**Comment by udebella** [comment]
On a discuté autour des web-components.

Le code que j'ai présenté est disponible sur mon [github](https://github.com/udebella/Github-jira-helper).
Pour aller plus loin : 
* [Le site officiel](https://www.webcomponents.org)
* [La doc MDN](https://developer.mozilla.org/en-US/docs/Web/Web_Components) est pas mal aussi
